[package]
authors = ["rise0chen <rise0chen@163.com>"]
categories = ["rust-patterns"]
description = "makes all the properties of a struct type an optional property"
documentation = "https://docs.rs/partial_derive"
edition = "2018"
keywords = ["struct", "field"]
license = "MIT"
name = "partial_derive"
readme = "README.md"
repository = "https://github.com/rise0chen/partial_derive"
version = "0.1.0"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[lib]
proc-macro = true
